config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#index'

  resources :families, only: [:new, :index, :show, :create]
  resources :members, only: [:new, :index, :show, :create]
  
end

app/models/addresses.rb
class Address < ApplicationRecord
  validates :line1, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :kind, presence: true
  belongs_to :member, inverse_of: :address
  validates_presence_of :member
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	enum kind: [ :email, :phone, :fax, :online, :other ]
  validates :point, :kind, :name, :preferred, presence: true

  belongs_to :member, inverse_of: :contacts
  validates_presence_of :member
end

app/models/email.rb
class Email < ApplicationRecord
  validates :email, presence: true
  validates :kind, presence: true
  belongs_to :member, inverse_of: :emails
  validates_presence_of :member
end

app/models/member.rb
class Member < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  # validates :birth_date, presence: true

  has_many :contacts, dependent: :destroy, inverse_of: :member
  has_many :addresses, dependent: :destroy, inverse_of: :member

  accepts_nested_attributes_for :contacts, :addresses, allow_destroy: true

  has_parents(options = {current_spouse: true})

  NULL_ATTRS = [
    :mid_name, 
    :aka, 
    :birth_date, 
    :mother_id, 
    :father_id, 
    :death_date, 
    :current_spouse_id
  ]

  before_save :nil_if_blank

  def goes_by
    !!aka ? aka : first_name
  end

  def initials
    (goes_by[0] + ( !!mid_name ? mid_name[0] : "" ) + last_name[0]).upcase
  end

  def full_name
    "#{first_name} #{mid_name} #{last_name}"
  end

  def age
    now = Time.now.utc.to_date
    years = now.year - self.birth_date.year 
    bday_before_this_month = now.month > self.birth_date.month
    bday_this_month = now.month == self.birth_date.month
    bday_before_today = now.day >= self.birth_date.day
    years - (( bday_before_this_month || ( bday_this_month && bday_before_today )) ? 0 : 1 )
  end

  # initial method produces an rgb value from each initial, using the mean value when a middle name is absent
  # def color
  #   def char_to_num(letter)
  #     "a".upto("z").to_a.index(letter)
  #   end
  #   mid_average = ((char_to_num(initials[0]) - char_to_num(initials[1])).abs/2 + char_to_num(initials[0]))
  #   mid_average = "a".upto("z").to_a[mid_average]
  #   mid = !!mid_name ? mid_name[0] : mid_average
  #   color = []
  #   initials.insert(1, mid).each_char { i color << (char_to_num(i) * 10) }
  #   color.to_s[1..-2]
  # end

  # this method produces a numeric sum based on the initials and scales to a hue hsl value
  def color
    def char_to_num(letter)
      "A".upto("Z").to_a.index(letter)
    end
    hue = 0
    initials.each_char { |i| hue += char_to_num(i) }
    ((hue / (initials.length * 25.0)) * 360).floor
  end

  protected

  def nil_if_blank
    NULL_ATTRS.each { |attr| self[attr] = nil if self[attr].blank? }
  end

end

app/models/phone.rb
class Phone < ApplicationRecord
  validates :phone, presence: true
  validates :kind, presence: true
  belongs_to :member, inverse_of: :phone
  validates_presence_of :member
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  def index
    @families = Family.all
  end

  def new
    @family = Family.new
  end

  def create
    @family = Family.new(family_params)

    if @family.save
      flash[:notice] = "Family added successfully"
      redirect_to family_path(@family)
    elsif
      flash[:alert] = "family could not be created"
      render :new
    end
  end

  def show
    @family = Family.find(params[:id])
  end

  private

  def family_params
    params.require(:family).permit(:surname, :matriarch, :patriarch, :city, :state, :anniversary)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = Member.all
  end

  def new
    @member = Member.new
    @member.contacts.build

  end

  def create
    @member = Member.new(member_params)
    # @email = Email.new(member_params)
    # @member.emails << @email

    if @member.save
      flash[:notice] = "Member added successfully"
      redirect_to member_path(@member)
    elsif
      flash[:alert] = "member could not be created"
      render :new
    end
  end

  def show
    @member = Member.find(params[:id])
  end

  private

  def member_params
    params.require(:member).permit(:first_name, :last_name, :mid_name, :aka, :birth_date,
      contacts_attributes: [:point, :kind, :name, :preferred],
      addresses_attributes: [:line1, :line2, :city, :state, :zip, :kind]
      )
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/families/index.html.erb
<h1>Families</h1>
<%= link_to "Add New Family", new_family_path %>
<br/><br/>
<% @families.each do |fam| %>
  <div>
    <%= link_to fam.surname, family_path(fam) %>
  </div>
<% end %>

app/views/families/new.html.erb
<h1>New Family Form</h1>

<% if @family.errors %>
  <div class="errors">
    <%= @family.errors.full_messages.to_sentence %>
  </div>
<% end %>

<%= form_for @family, url: "/families" do |f| %>
  <formfield>
    <%= f.label :surname %>
    <%= f.text_field :surname %>
  </formfield>
  <formfield>
    <%= f.label :matriarch %>
    <%= f.text_field :matriarch %>
    <%= f.label :patriarch %>
    <%= f.text_field :patriarch %>
    <%= f.label :city %>
    <%= f.text_field :city %>
    <%= f.label :state %>
    <%= f.text_field :state %>
    <%= f.label :anniversary %>
    <%= f.date_field :anniversary %>
  </formfield>
  <formfield>
    <%= f.submit "Add Family" %>
  </formfield>
<% end %>

app/views/families/show.html.erb
<h1>The <%= @family.surname %> Family</h1>
<%= @family.patriarch %> and <%= @family.matriarch %> of <%= "#{@family.city}, " if !!@family.city %><%= @family.state %><br/>
<%= " Anniversary: #{@family.anniversary}" if !!@family.anniversary %><br/>

<div class="family-members">
<h4>Family Members</h4>
  <ul>
    <% @family.members.each do |member| %>
      <li> <%= link_to member.full_name, member %> </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>React Rails Monolith</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_avatar.html.erb
<div class="avatar <%= member.initials %>" >
	<style>
		.avatar:after { background: hsl(<%= member.color %>, 70%, 50%); }
	</style>
	<div>
		<%= (member.initials[0] + member.initials[-1]) %>
	</div>
</div>

app/views/members/_branch.html.erb
<div class="branch" id="<%= member.id %>" >
	<div class="branch-members" >
		<%= render partial: "members/card", object: member, as: 'member' %>
		<% if !!member.current_spouse %>
			<%= render partial: "members/card", object: member.current_spouse, as: "member", locals: {spouse: "spouse" } %>
		<% end %>
	</div>
	<% if !!member.children.first %>
		<i class="expand hide fas fa-chevron-circle-up" ></i>
<!-- 		<script>
			$(this).find(".expand").click(function(event) {
				this.toggleClass("fa-chevron-circle-down fa-chevron-circle-up");
			});
		</script>
 -->		<div class="children" >
			<% member.children.each do |mem| %>
				<%= render partial: "branch", object: mem, as: "member" %>
			<% end %>
		</div>
	<% end %>
</div>

app/views/members/_card.html.erb
<div class="member-card<%= defined?(spouse) ? " spouse" : "" %>" >
	<%= link_to member do %>
		<%= render partial: "members/avatar", object: member, as: 'member' %>
		<%= member.goes_by %><br/>
		<%= member.age %>
	<% end %>
</div>

app/views/members/index.html.erb
<h1>Members</h1>
<%= link_to "Add New Family Member", new_member_path %>
<br/><br/>
<% @members.each do |mem| %>
  <div>
    <%= link_to "#{mem.first_name} #{mem.last_name}", member_path(mem) %>
  </div>
<% end %>

app/views/members/new.html.erb
<h1>New Family Member Form</h1>

<% if @member.errors %>
  <div class="errors">
    <%= @member.errors.full_messages.to_sentence %>
  </div>
<% end %>

<%= form_for @member, url: "/members" do |f| %>
  <formfield>
    <%= f.label :family_ids %><br/>
    <%= f.collection_check_boxes :family_ids, Family.all, :id, :surname do |check| %>
    <%= check.check_box %><%= check.label %><br/>
    <% end %>
    <%= link_to "Add a new family", new_family_path %><br/>
    <%= f.label :first_name %><br/>
    <%= f.text_field :first_name %><br/>
    <%= f.label :mid_name %><br/>
    <%= f.text_field :mid_name %><br/>
    <%= f.label :last_name %><br/>
    <%= f.text_field :last_name %><br/>
    <%= f.label :aka %><br/>
    <%= f.text_field :aka %><br/>
    <%= f.label :birth_date %><br/>
    <%= f.date_field :birth_date %><br/>
    Emails:
    <ul>
      <%= f.fields_for :emails do |email_f| %>
        <li>
          <% email_f.label :email %>
          <%= email_f.text_field :email %>

          <%= email_f.label :kind %>
          <% email_kinds = ["Personal", "Work", "Primary"] %>
          <%= email_f.select(:kind) do %>
            <% email_kinds.each do |i|  %>
              <%= content_tag(:option, i, value: i) %>
            <% end %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </formfield>
  <formfield>
    <%= f.submit "Add Family Member" %>
  </formfield>
<% end %>

app/views/members/show.html.erb
<div class="member" > 
	<div class="member-show">
		<%= render partial: "members/avatar", object: @member, as: 'member' %>
	<h1> <%= @member.goes_by+" "+@member.last_name %> </h1>
	<p>
		Full  Name <br/>
		<%= @member.full_name %>
	</p>
	<p>
		Born On <br/>
		<%= @member.birth_date.strftime("%A, %B #{@member.birth_date.day}, %Y") %><br/>
	</p>
	<p>
		<% if !!@member.mother && !!@member.father %>
			Parents <br/>
			<%= "#{@member.father.first_name} and #{@member.mother.first_name}" %>
		<% end %>
	</p>
	</div>
	<div class="overview">
		<% if !!@member.mother && !!@member.father %>
			<%= render partial: "branch", object: @member.father, as: 'member' %>
		<% else %>
			<%= render partial: "branch", object:  @member, as: 'member' %>
		<% end %>
	</div>
</div>

app/views/static_pages/index.html.erb
<div id="app">
</div>